In [1]:
import pandas as pd
import numpy as np
import os
import sys

In [2]:
class StandardScaler:
    def __init__(self):
        self.mean = None
        self.std = None

    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)

    def transform(self, X):
        return (X - self.mean) / self.std

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)


In [3]:
X = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 1100.0],
    [3.0, 400.0, 1200.0]
])

scaler = StandardScaler()

# Fit and transform
X_scaled = scaler.fit_transform(X)

# Print results
print("Original X:\n", X)
print("Scaled X:\n", X_scaled)

# Check means and stds of scaled data (should be ~0 and ~1)
print("Means after scaling:", np.mean(X_scaled, axis=0))
print("Stds after scaling:", np.std(X_scaled, axis=0))

Original X:
 [[1.0e+00 2.0e+02 1.0e+03]
 [2.0e+00 3.0e+02 1.1e+03]
 [3.0e+00 4.0e+02 1.2e+03]]
Scaled X:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Means after scaling: [0. 0. 0.]
Stds after scaling: [1. 1. 1.]


In [6]:
class MinMaxScaler:
    def __init__(self):
        self.max = None
        self.min = None

    def fit(self, X):
        X = np.array(X, dtype=float)
        self.max = np.max(X, axis=0)
        self.min = np.min(X, axis=0)

    def transform(self, X):
        X = np.array(X, dtype=float)
        denom = self.max - self.min
        # Works for both scalars and arrays
        denom = np.where(denom == 0, 1, denom)
        return (X - self.min) / denom

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [7]:
X = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 1100.0],
    [3.0, 400.0, 1200.0]
])

scaler = MinMaxScaler()

# Fit and transform
X_scaled = scaler.fit_transform(X)

# Print results
print("Original X:\n", X)
print("Scaled X:\n", X_scaled)

# Check means and stds of scaled data (should be ~0 and ~1)
print("Means after scaling:", np.mean(X_scaled, axis=0))
print("Stds after scaling:", np.std(X_scaled, axis=0))

Original X:
 [[1.0e+00 2.0e+02 1.0e+03]
 [2.0e+00 3.0e+02 1.1e+03]
 [3.0e+00 4.0e+02 1.2e+03]]
Scaled X:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
Means after scaling: [0.5 0.5 0.5]
Stds after scaling: [0.40824829 0.40824829 0.40824829]


In [8]:
class MaxAbsScaler:
    def __init__(self):
        self.max = None

    def fit(self, X):
        X = np.array(X, dtype=float)
        self.max = np.max(np.abs(X), axis=0)

    def transform(self, X):
        X = np.array(X, dtype=float)
        safe_max = np.where(self.max == 0, 1, self.max)
        return X / safe_max

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [9]:
X = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 1100.0],
    [3.0, 400.0, 1200.0]
])

scaler = MaxAbsScaler()

# Fit and transform
X_scaled = scaler.fit_transform(X)

# Print results
print("Original X:\n", X)
print("Scaled X:\n", X_scaled)

# Check means and stds of scaled data (should be ~0 and ~1)
print("Means after scaling:", np.mean(X_scaled, axis=0))
print("Stds after scaling:", np.std(X_scaled, axis=0))

Original X:
 [[1.0e+00 2.0e+02 1.0e+03]
 [2.0e+00 3.0e+02 1.1e+03]
 [3.0e+00 4.0e+02 1.2e+03]]
Scaled X:
 [[0.33333333 0.5        0.83333333]
 [0.66666667 0.75       0.91666667]
 [1.         1.         1.        ]]
Means after scaling: [0.66666667 0.75       0.91666667]
Stds after scaling: [0.27216553 0.20412415 0.06804138]


In [10]:
class RobustScaler:
    def __init__(self):
        self.q1 = None
        self.q2 = None
        self.q3 = None

    def fit(self, X):
        X = np.array(X, dtype=float)
        self.q1 = np.quantile(X, 0.25, axis=0)
        self.q2 = np.quantile(X, 0.5, axis=0)
        self.q3 = np.quantile(X, 0.75, axis=0)

    def transform(self, X):
        X = np.array(X, dtype=float)
        iqr = self.q3 - self.q1
        safe_iqr = np.where(iqr == 0, 1, iqr)
        return (X-self.q2)/safe_iqr

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [11]:
X = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 1100.0],
    [3.0, 400.0, 1200.0]
])

scaler = MaxAbsScaler()

# Fit and transform
X_scaled = scaler.fit_transform(X)

# Print results
print("Original X:\n", X)
print("Scaled X:\n", X_scaled)

# Check means and stds of scaled data (should be ~0 and ~1)
print("Means after scaling:", np.mean(X_scaled, axis=0))
print("Stds after scaling:", np.std(X_scaled, axis=0))

Original X:
 [[1.0e+00 2.0e+02 1.0e+03]
 [2.0e+00 3.0e+02 1.1e+03]
 [3.0e+00 4.0e+02 1.2e+03]]
Scaled X:
 [[0.33333333 0.5        0.83333333]
 [0.66666667 0.75       0.91666667]
 [1.         1.         1.        ]]
Means after scaling: [0.66666667 0.75       0.91666667]
Stds after scaling: [0.27216553 0.20412415 0.06804138]
