In [1]:
import pandas as pd
import numpy as np
import os
import sys

In [2]:
class StandardScaler:
    def __init__(self):
        self.mean = None
        self.std = None

    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)

    def transform(self, X):
        return (X - self.mean) / self.std

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)


In [3]:
X = np.array([
    [1.0, 200.0, 1000.0],
    [2.0, 300.0, 1100.0],
    [3.0, 400.0, 1200.0]
])

scaler = StandardScaler()

# Fit and transform
X_scaled = scaler.fit_transform(X)

# Print results
print("Original X:\n", X)
print("Scaled X:\n", X_scaled)

# Check means and stds of scaled data (should be ~0 and ~1)
print("Means after scaling:", np.mean(X_scaled, axis=0))
print("Stds after scaling:", np.std(X_scaled, axis=0))

Original X:
 [[1.0e+00 2.0e+02 1.0e+03]
 [2.0e+00 3.0e+02 1.1e+03]
 [3.0e+00 4.0e+02 1.2e+03]]
Scaled X:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Means after scaling: [0. 0. 0.]
Stds after scaling: [1. 1. 1.]
